In [1]:
import pandas as pd
data = pd.DataFrame({'group': ['a', 'a', 'a', 'b','b', 'b', 'c', 'c','c'],
                 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

  group  ounces
0     a     4.0
1     a     3.0
2     a    12.0
3     b     6.0
4     b     7.5
5     b     8.0
6     c     3.0
7     c     5.0
8     c     6.0

In [6]:
import pandas as pd
data = pd.DataFrame({'group': ['a', 'a', 'a', 'b','b', 'b', 'c', 'c','c'],
                 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

  group  ounces
0     a     4.0
1     a     3.0
2     a    12.0
3     b     6.0
4     b     7.5
5     b     8.0
6     c     3.0
7     c     5.0
8     c     6.0

In [7]:
data.sort_values(by=['group','ounces'], ascending=[False, True], inplace=True)
data

  group  ounces
6     c     3.0
7     c     5.0
8     c     6.0
3     b     6.0
4     b     7.5
5     b     8.0
1     a     3.0
0     a     4.0
2     a    12.0

In [8]:
data.sort_values(by=['group','ounces'], ascending=[True, False], inplace=True)
data

  group  ounces
2     a    12.0
0     a     4.0
1     a     3.0
5     b     8.0
4     b     7.5
3     b     6.0
8     c     6.0
7     c     5.0
6     c     3.0

In [29]:
import pandas as pd
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami','corned beef', 'Bacon', 'pastrami', 'honey ham','nova lox'],
                 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [30]:
meat_to_animal = {
'bacon': 'pig',
'pulled pork': 'pig',
'pastrami': 'cow',
'corned beef': 'cow',
'honey ham': 'pig',
'nova lox': 'salmon'
}

def meat2animal(series):
    if series["food"]=='bacon':
        return 'pig'
    elif series["food"]=='pulled pork':
        return 'pig'
    elif series["food"]=='pastrami':
        return 'cow'
    elif series["food"]=='corned beef':
        return 'cow'
    elif series["food"]=='honey ham':
        return 'pig'
    else:
        return 'salmon'

In [53]:
data['animal'] = data['food'].map(str.upper).map(meat_to_animal)
data

KeyError: 'food'

In [46]:
data.drop('animal', axis='columns', inplace=False)  # dropping/removing a column
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [55]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [56]:
bins = [18, 25, 35, 60, 100]

In [63]:
cats = pd.cut(ages,bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, object): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [47]:
data.add('animal', axis='index', inplace=True)  # dropping/removing a column
data

TypeError: f() got an unexpected keyword argument 'inplace'

In [25]:
import pandas as pd
data = pd.DataFrame({'food':['teja','g','ghd'], 'shoes':['adi','poma','spaks']})
data
te = {
    'teja': 'bhuka',
    'g': 'pyasa',
    'ghd':'hagra'
}
def tejas(series):
    if series["food"]=='teja':
    return 'adi'
    elif  series["food"]=='pyasa':
    return 'poma'
    elif series["food"]=='hagra':
    return 'spaks'
    else:
    return 'h'

IndentationError: expected an indented block (<ipython-input-25-d2aaf5b13e92>, line 11)

In [52]:
import pandas as pd
data = pd.DataFrame(np.arange(16).reshape((4, 4)),index=['Ohio', 'Colorado', 'New York','bc'],columns=['one', 'two', 'three', 'four'])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11
bc         12   13     14    15

In [13]:
import pandas as pd
data = pd.DataFrame({'group': ['a'] * 3 + ['b'] * 4, 'ounces': [1,5,4,2,7,3,5]})
data

  group  ounces
0     a       1
1     a       5
2     a       4
3     b       2
4     b       7
5     b       3
6     b       5

In [3]:
import pandas as pd
data = pd.DataFrame({'name':['t', 'r'],
                    'no':[4,5]})
data

  name  no
0    t   4
1    r   5

data.describe()

In [4]:
data.describe()

             no
count  2.000000
mean   4.500000
std    0.707107
min    4.000000
25%    4.250000
50%    4.500000
75%    4.750000
max    5.000000

In [39]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'data1' : np.random.randn(7),
                   'data2' : np.random.randn(7)})

df.assign(ratio = df['data1'] / df['data2'])

      data1     data2      ratio
0  0.785770 -1.286727  -0.610673
1 -0.987229 -1.366545   0.722427
2 -0.298227 -0.998581   0.298651
3  0.547640  0.578544   0.946583
4  0.280216  0.620790   0.451387
5 -0.552932  0.392840  -1.407525
6 -1.342277  0.020717 -64.789654

In [40]:
data.drop('ratio', axis='columns', inplace=True)  # dropping/removing a column
data

ValueError: labels ['ratio'] not contained in axis

In [5]:
data.sort_values(by=['group','ounces'], ascending=[False, True], inplace=True)
data

KeyError: 'group'

In [65]:
import pandas as pd
print(pd.__version__)

0.18.1

In [66]:
pd.read_json?

In [67]:
df = pd.read_json("http://localhost:8888/edit/Desktop/python_data_science/users.dat")

df.head(5)

ValueError: Expected object or value

In [69]:
import movies as ms

ImportError: No module named movies

In [70]:
data = pd.read_csv('output_list.txt', sep=" ", header = None)
data.columns = ["a", "b", "c", "etc."]

IOError: File output_list.txt does not exist

In [72]:
data = pd.read_csv('users1.txt', sep=" ", header = None)
data.columns = ["a", "b", "c", "d"]
print data

ValueError: Length mismatch: Expected axis has 1 elements, new values have 4 elements

In [76]:
import pandas as pd    

with open('C:/Users/katariya/Desktop/python_data_science/users.dat','r') as f:
    df = pd.DataFrame(l.rstrip().split() for l in f)

print(df)

                           0
0         1::F::1::10::48067
1        2::M::56::16::70072
2        3::M::25::15::55117
3         4::M::45::7::02460
4        5::M::25::20::55455
5         6::F::50::9::55117
6         7::M::35::1::06810
7        8::M::25::12::11413
8        9::M::25::17::61614
9        10::F::35::1::95370
10       11::F::25::1::04093
11      12::M::25::12::32793
12       13::M::45::1::93304
13       14::M::35::0::60126
14       15::M::25::7::22903
15       16::F::35::0::20670
16       17::M::50::1::95350
17       18::F::18::3::95825
18       19::M::1::10::48073
19      20::M::25::14::55113
20      21::M::18::16::99353
21      22::M::18::15::53706
22       23::M::35::0::90049
23       24::F::25::7::10023
24       25::M::18::4::01609
25       26::M::25::7::23112
26      27::M::25::11::19130
27       28::F::25::1::14607
28       29::M::35::7::33407
29       30::F::35::7::19143
...                      ...
6010  6011::M::35::15::80538
6011  6012::M::35::15::02871
6012  6013::F::25::20::32301
6013   6014::M::45::1::80634
6014   6015::F::25::9::80013
6015   6016::M::45::1::37209
6016   6017::F::35::7::21117
6017   6018::M::35::1::48906
6018   6019::M::25::0::10024
6019  6020::M::50::16::10023
6020  6021::M::25::12::08876
6021  6022::M::25::17::57006
6022   6023::M::25::0::43213
6023  6024::M::25::12::53705
6024   6025::F::25::1::32607
6025   6026::M::35::6::11210
6026   6027::M::18::4::20742
6027   6028::M::18::4::94133
6028   6029::F::25::1::23185
6029  6030::M::25::17::32618
6030   6031::F::18::0::45123
6031   6032::M::45::7::55108
6032  6033::M::50::13::78232
6033  6034::M::25::14::94117
6034   6035::F::25::1::78734
6035  6036::F::25::15::32603
6036   6037::F::45::1::76006
6037   6038::F::56::1::14706
6038   6039::F::45::0::01060
6039   6040::M::25::6::11106

[6040 rows x 1 columns]

In [77]:
import pandas as pd
data = pd.DataFrame({with open('C:/Users/katariya/Desktop/python_data_science/users.dat','r') as f:
    df = pd.DataFrame(l.rstrip().split() for l in f)

})
data

SyntaxError: invalid syntax (<ipython-input-77-eaabe7a3e103>, line 2)

In [78]:
data.sort_values(by='F')
data

KeyError: 'F'

In [83]:


import pandas as pd    

with open('C:/Users/katariya/Desktop/python_data_science/users.dat','r') as f:
    df = pd.DataFrame(l.rstr().split() for l in f)

print(df)

AttributeError: 'str' object has no attribute 'rstr'

In [80]:
data.sort_values(by=['data1'],  inplace=True)
data

KeyError: 'data1'

In [84]:
import pandas as pd    

with open('C:/Users/katariya/Desktop/python_data_science/users.dat','r') as f:
    df = pd.DataFrame(l.rstrip().sep() for l in f)

print(df)

                           0
0         1::F::1::10::48067
1        2::M::56::16::70072
2        3::M::25::15::55117
3         4::M::45::7::02460
4        5::M::25::20::55455
5         6::F::50::9::55117
6         7::M::35::1::06810
7        8::M::25::12::11413
8        9::M::25::17::61614
9        10::F::35::1::95370
10       11::F::25::1::04093
11      12::M::25::12::32793
12       13::M::45::1::93304
13       14::M::35::0::60126
14       15::M::25::7::22903
15       16::F::35::0::20670
16       17::M::50::1::95350
17       18::F::18::3::95825
18       19::M::1::10::48073
19      20::M::25::14::55113
20      21::M::18::16::99353
21      22::M::18::15::53706
22       23::M::35::0::90049
23       24::F::25::7::10023
24       25::M::18::4::01609
25       26::M::25::7::23112
26      27::M::25::11::19130
27       28::F::25::1::14607
28       29::M::35::7::33407
29       30::F::35::7::19143
...                      ...
6010  6011::M::35::15::80538
6011  6012::M::35::15::02871
6012  6013::F::25::20::32301
6013   6014::M::45::1::80634
6014   6015::F::25::9::80013
6015   6016::M::45::1::37209
6016   6017::F::35::7::21117
6017   6018::M::35::1::48906
6018   6019::M::25::0::10024
6019  6020::M::50::16::10023
6020  6021::M::25::12::08876
6021  6022::M::25::17::57006
6022   6023::M::25::0::43213
6023  6024::M::25::12::53705
6024   6025::F::25::1::32607
6025   6026::M::35::6::11210
6026   6027::M::18::4::20742
6027   6028::M::18::4::94133
6028   6029::F::25::1::23185
6029  6030::M::25::17::32618
6030   6031::F::18::0::45123
6031   6032::M::45::7::55108
6032  6033::M::50::13::78232
6033  6034::M::25::14::94117
6034   6035::F::25::1::78734
6035  6036::F::25::15::32603
6036   6037::F::45::1::76006
6037   6038::F::56::1::14706
6038   6039::F::45::0::01060
6039   6040::M::25::6::11106

[6040 rows x 1 columns]

In [93]:
import pandas as pd    

with open('C:/Users/katariya/Desktop/python_data_science/users.dat','r') as f:
    df = pd.DataFrame(l.rstrip().split() for l in f)
    df.split(",")
print(p)

AttributeError: 'DataFrame' object has no attribute 'split'

In [94]:
 pd.read_csv('users1.csv')

IOError: File users1.csv does not exist

In [95]:
 pd.read_csv('use.csv')

         ﻿1::F::1::10::48067
0        2::M::56::16::70072
1        3::M::25::15::55117
2         4::M::45::7::02460
3        5::M::25::20::55455
4         6::F::50::9::55117
5         7::M::35::1::06810
6        8::M::25::12::11413
7        9::M::25::17::61614
8        10::F::35::1::95370
9        11::F::25::1::04093
10      12::M::25::12::32793
11       13::M::45::1::93304
12       14::M::35::0::60126
13       15::M::25::7::22903
14       16::F::35::0::20670
15       17::M::50::1::95350
16       18::F::18::3::95825
17       19::M::1::10::48073
18      20::M::25::14::55113
19      21::M::18::16::99353
20      22::M::18::15::53706
21       23::M::35::0::90049
22       24::F::25::7::10023
23       25::M::18::4::01609
24       26::M::25::7::23112
25      27::M::25::11::19130
26       28::F::25::1::14607
27       29::M::35::7::33407
28       30::F::35::7::19143
29       31::M::56::7::06840
...                      ...
6009  6011::M::35::15::80538
6010  6012::M::35::15::02871
6011  6013::F::25::20::32301
6012   6014::M::45::1::80634
6013   6015::F::25::9::80013
6014   6016::M::45::1::37209
6015   6017::F::35::7::21117
6016   6018::M::35::1::48906
6017   6019::M::25::0::10024
6018  6020::M::50::16::10023
6019  6021::M::25::12::08876
6020  6022::M::25::17::57006
6021   6023::M::25::0::43213
6022  6024::M::25::12::53705
6023   6025::F::25::1::32607
6024   6026::M::35::6::11210
6025   6027::M::18::4::20742
6026   6028::M::18::4::94133
6027   6029::F::25::1::23185
6028  6030::M::25::17::32618
6029   6031::F::18::0::45123
6030   6032::M::45::7::55108
6031  6033::M::50::13::78232
6032  6034::M::25::14::94117
6033   6035::F::25::1::78734
6034  6036::F::25::15::32603
6035   6037::F::45::1::76006
6036   6038::F::56::1::14706
6037   6039::F::45::0::01060
6038   6040::M::25::6::11106

[6039 rows x 1 columns]

In [96]:
 pd.read_csv(StringIO(data), names=['series', 'bar', 'baz'], header=0)

NameError: name 'StringIO' is not defined

C:\Users\katariya\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  if __name__ == '__main__':
C:\Users\katariya\Anaconda2\lib\site-packages\ipykernel\__main__.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  from ipykernel import kernelapp as app

In [105]:

datam=pd.read_table('movies.dat',sep='::',names=['movies-id','title','gernes'])
datam

C:\Users\katariya\Anaconda2\lib\site-packages\ipykernel\__main__.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  from ipykernel import kernelapp as app

,movies-id,title,gernes
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children's
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller
10,11,"American President, The (1995)",Comedy|Drama|Romance
11,12,Dracula: Dead and Loving It (1995),Comedy|Horror
12,13,Balto (1995),Animation|Children's
13,14,Nixon (1995),Drama
14,15,Cutthroat Island (1995),Action|Adventure|Romance
15,16,Casino (1995),Drama|Thriller
16,17,Sense and Sensibility (1995),Drama|Romance
17,18,Four Rooms (1995),Thriller
18,19,Ace Ventura: When Nature Calls (1995),Comedy
19,20,Money Train (1995),Action
20,21,Get Shorty (1995),Action|Comedy|Drama
21,22,Copycat (1995),Crime|Drama|Thriller
22,23,Assassins (1995),Thriller
23,24,Powder (1995),Drama|Sci-Fi
24,25,Leaving Las Vegas (1995),Drama|Romance
25,26,Othello (1995),Drama
26,27,Now and Then (1995),Drama
27,28,Persuasion (1995),Romance
28,29,"City of Lost Children, The (1995)",Adventure|Sci-Fi
29,30,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Drama
...,...,...,...
3853,3923,Return of the Fly (1959),Horror|Sci-Fi
3854,3924,Pajama Party (1964),Comedy
3855,3925,Stranger Than Paradise (1984),Comedy
3856,3926,Voyage to the Bottom of the Sea (1961),Adventure|Sci-Fi
3857,3927,Fantastic Voyage (1966),Adventure|Sci-Fi
3858,3928,Abbott and Costello Meet Frankenstein (1948),Comedy|Horror
3859,3929,"Bank Dick, The (1940)",Comedy
3860,3930,"Creature From the Black Lagoon, The (1954)",Horror
3861,3931,"Giant Gila Monster, The (1959)",Horror|Sci-Fi
3862,3932,"Invisible Man, The (1933)",Horror|Sci-Fi
3863,3933,"Killer Shrews, The (1959)",Horror|Sci-Fi
3864,3934,Kronos (1957),Sci-Fi
3865,3935,Kronos (1973),Horror
3866,3936,"Phantom of the Opera, The (1943)",Drama|Thriller
3867,3937,Runaway (1984),Sci-Fi|Thriller
3868,3938,"Slumber Party Massacre, The (1982)",Horror
3869,3939,"Slumber Party Massacre II, The (1987)",Horror
3870,3940,"Slumber Party Massacre III, The (1990)",Horror
3871,3941,Sorority House Massacre (1986),Horror
3872,3942,Sorority House Massacre II (1990),Horror
3873,3943,Bamboozled (2000),Comedy
3874,3944,Bootmen (2000),Comedy|Drama
3875,3945,Digimon: The Movie (2000),Adventure|Animation|Children's
3876,3946,Get Carter (2000),Action|Drama|Thriller
3877,3947,Get Carter (1971),Thriller
3878,3948,Meet the Parents (2000),Comedy
3879,3949,Requiem for a Dream (2000),Drama
3880,3950,Tigerland (2000),Drama
3881,3951,Two Family House (2000),Drama
3882,3952,"Contender, The (2000)",Drama|Thriller

In [ ]:
datam=pd.read_table(users.dat',sep='::',names=['movies-id','title','gernes'])
datam